<a href="https://colab.research.google.com/github/olcaykursun/ML/blob/main/Summer24/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
from sklearn import datasets

# Load the Iris dataset
iris = datasets.load_iris()
iris_data = iris.data
iris_target = iris.target

n_samples = len(iris_data)

#iris_data[0,0]=6
#print(iris.data[0,0])

In [35]:
abcd = (np.array([1,2]), np.array([3,4]), [5,6], 7)
a=abcd[0]
b=abcd[1]
c=abcd[2]
d=abcd[3]

a+=1000
b=np.array([33,44])
c[-1]=66
c.append(666)
d=77

print(a)
print(b)
print(c)
print(d)
print(abcd)


[1001 1002]
[33 44]
[5, 66, 666]
77
(array([1001, 1002]), array([3, 4]), [5, 66, 666], 7)


In [37]:
# Function to calculate the distance between each row of the dataset
def calculate_distances(dataset):
    n_rows = dataset.shape[0]
    euc_distances = np.zeros((n_rows, n_rows))
    manh_distances = np.zeros((n_rows, n_rows))
    for i, row_i in enumerate(dataset):
        for j, row_j in enumerate(dataset):
            # Euclidean distances
            euc_distances[i, j] = np.sqrt(np.sum((row_i - row_j)**2)) #np.linalg.norm(row_i - row_j)

            # Manhattan distances
            manh_distances[i, j] = np.sum(np.abs(row_i - row_j))

    return euc_distances, manh_distances

euc_distances, manh_distances = calculate_distances(iris_data)


In [38]:
#let's apply leave-one-out
n_correct_classification = 0
for i in range(n_samples):
    # Calculate distances from the i-th sample to all samples in the training set
    distances = manh_distances[i] #should return 1-by-150 distances
    distances[i] = np.inf

    nearest_index = np.argmin(distances)
    if iris_target[i] == iris_target[nearest_index]:
        n_correct_classification += 1

acc = n_correct_classification / n_samples
print(f'{acc=:.3f}')


acc=0.953


In [41]:
distances

array([6.6, 6.3, 6.8, 6.6, 6.8, 6.2, 6.9, 6.5, 6.9, 6.4, 6.4, 6.6, 6.5,
       7.3, 6.6, 6.6, 6.6, 6.5, 5.9, 6.7, 5.9, 6.5, 7.6, 5.8, 6.3, 6. ,
       6.2, 6.4, 6.4, 6.5, 6.3, 5.9, 7.1, 6.9, 6.3, 6.6, 6.3, 7. , 6.9,
       6.4, 6.7, 7.4, 7.1, 6.1, 6.2, 6.3, 6.7, 6.8, 6.5, 6.5, 2.1, 1.6,
       1.6, 2.7, 1.6, 1.5, 1.3, 4.2, 1.8, 2.6, 4.3, 1.2, 2.8, 1.1, 2.4,
       2. , 1.2, 2.2, 2. , 2.7, 0.5, 2. , 1.4, 1.4, 1.9, 1.8, 1.8, 1. ,
       1.1, 3. , 3. , 3.2, 2.2, 0.6, 1.4, 1.3, 1.6, 2.3, 1.8, 2.5, 2.1,
       1.1, 2.2, 4.2, 2. , 1.7, 1.7, 1.7, 4.1, 1.9, 2.3, 0.5, 2.3, 1. ,
       1.7, 3.5, 2.2, 2.7, 2. , 3.6, 1. , 1.1, 1.6, 1. , 0.9, 1.4, 1. ,
       4.6, 4.5, 1.3, 2.3, 0.9, 3.8, 0.9, 2. , 2.4, 0.8, 0.4, 1.5, 2.2,
       2.8, 4.3, 1.6, 0.9, 1.5, 3.3, 1.9, 1. , 0.4, 1.7, 2. , 1.6, 0.5,
       2.4, 2.4, 1.4, 1.1, 0.9, 1.5, inf])

In [42]:
nearest_neighbors_indices = np.zeros(n_samples, dtype=int)

for i in range(n_samples):
    # Calculate distances from the i-th sample to all samples in the training set
    distances = euc_distances[i] #should return 1-by-150 distances
    distances[i] = np.inf

    nearest_neighbors_indices[i] = np.argmin(distances)

nearest_neighbors_indices


array([ 17,  34,  47,  47,  37,  18,  47,  39,  38,  34,  48,  29,   1,
        38,  33,  33,  10,   0,   5,  21,  31,  19,   6,  26,  11,  34,
        23,  28,  27,  30,  29,  20,  33,  32,   9,  49,  10,   4,   8,
         7,  17,   8,  38,  26,  46,   1,  19,   3,  10,   7,  52,  56,
        50,  89,  58,  66,  51,  93,  75,  89,  93,  96,  92,  91,  82,
        75,  84,  92,  87,  80, 138,  97, 133,  63,  97,  65,  58,  52,
        91,  81,  81,  80,  92, 133,  66,  56,  52,  68,  95,  53,  94,
        63,  82,  57,  99,  96,  95,  74,  57,  96, 136, 142, 125, 116,
       132, 122,  84, 130, 128, 143, 147, 147, 139, 101, 121, 148, 137,
       131, 122,  72, 143, 101, 105, 126, 120, 129, 123, 138, 132, 125,
       107, 117, 128,  83, 103, 130, 148, 116, 127, 112, 144, 145, 101,
       120, 140, 141, 123, 110, 136, 127])

In [43]:
preds = iris_target[nearest_neighbors_indices]
preds

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
preds == iris_target

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,

In [8]:
sum(preds == iris_target)

144

In [9]:
acc = (preds == iris_target).mean()
print(f'{acc=:.3f}')

acc=0.960


In [47]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import LeaveOneOut

# Initialize the KNN classifier with Manhattan distance and k=1
knn = KNeighborsClassifier(n_neighbors=1, p=1)  # p=1 for Manhattan distance

# Initialize Leave-One-Out Cross-Validation
loo = LeaveOneOut()

# Initialize variables to store results
n_correct_classification = 0

X = iris.data
y = iris.target

# Perform Leave-One-Out Cross-Validation
for train_index, test_index in loo.split(X): #this gives us 150 pairs of train&test
    #print(train_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Fit KNN classifier on training data
    knn.fit(X_train, y_train)

    # Predict on test data
    y_pred = knn.predict(X_test)

    # Count correct predictions
    if y_pred == y_test:
        n_correct_classification += 1

# Calculate accuracy
accuracy = n_correct_classification / n_samples
print(f'Accuracy with scikit-LOO and scikit-KNN: {accuracy:.3f}')


Accuracy with scikit-LOO and scikit-KNN: 0.953


In [45]:
test_index

array([149])

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=120)

knn1 = KNeighborsClassifier(n_neighbors=1, p=1)
knn2 = KNeighborsClassifier(n_neighbors=1, p=2)

# Fit the KNN classifier on the training data
knn1.fit(X_train, y_train)
knn2.fit(X_train, y_train)

# Predict on the test data
y_pred1 = knn1.predict(X_test)
y_pred2 = knn2.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred1)
print(f'MANH: Accuracy with train_test_split and scikit-KNN: {accuracy:.3f}')

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred2)
print(f'EUC: Accuracy with train_test_split and scikit-KNN: {accuracy:.3f}')


MANH: Accuracy with train_test_split and scikit-KNN: 0.942
EUC: Accuracy with train_test_split and scikit-KNN: 0.942


In [50]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0])

In [65]:
from sklearn.metrics.pairwise import manhattan_distances

# Calculate Manhattan distances between training and test samples
distances = manhattan_distances(X_test, X_train)

# Iterate through each test sample to find nearest neighbor
n_correct_classification = 0
for i in range(len(X_test)):
    # Find the index of the nearest neighbor in the training set
    nearest_index = np.argmin(distances[i])

    my_pred = y_train[nearest_index]
    # Compare the target values
    if y_test[i] == my_pred:
        n_correct_classification += 1

# Calculate accuracy
acc = n_correct_classification / len(X_test)
print(f'Accuracy using nearest neighbor with Manhattan distance: {acc:.3f}')


Accuracy using nearest neighbor with Manhattan distance: 0.942


In [69]:
#Let's try LOO this time calling manhattan_distances for every iteration
from sklearn.metrics.pairwise import euclidean_distances

# Calculate Manhattan distances for each test sample to all training samples
n_correct_classification = 0
for i in range(n_samples):
    test_sample = X[i, :]  # Get the i-th test sample
    train_samples = np.delete(X, i, axis=0)  # Remove the i-th sample from training set
    distances = euclidean_distances([test_sample], train_samples)  # Calculate distances

    # Find the index of the nearest neighbor
    nearest_index = np.argmin(distances)

    # Compare the target values
    if y[i] == y[nearest_index]:
        n_correct_classification += 1

# Calculate accuracy
acc = n_correct_classification / n_samples
print(f'Accuracy using nearest neighbor with Manhattan distance: {acc:.3f}')


Accuracy using nearest neighbor with Manhattan distance: 0.960
