<a href="https://colab.research.google.com/github/olcaykursun/ML/blob/main/dot_outer_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

print(np.dot([3,4], [3,4]))

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a[:, np.newaxis])
print(a.reshape(-1,1))

# Manual 2D product without outer
result = a[:, np.newaxis] * b
print(result)

result = a[:, np.newaxis] * b[np.newaxis, :]
print(result)

result = np.outer(a,b)
print(result)


25
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [0, 2]])

# Matrix multiplication using np.dot
result_dot = np.dot(A, B)

# Matrix multiplication using @ operator
result_at = A @ B

print(result_dot)
print(result_at)


[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
