<a href="https://colab.research.google.com/github/olcaykursun/ML/blob/main/PandasNumpyTutorial4ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
# PandasNumpyTutorial4ML
# CSCI 6200 - Fall 2023 - Dr. Olcay Kursun
"""

import pandas as pd
import numpy as np


In [ ]:
print([1,2])
print(np.array([1,2]))

[1, 2]
[1 2]


In [ ]:
print(type([1,2]))
print(type(np.array([1,2])))


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(repr([1,2]))
print(repr(np.array([1,2])))

[1, 2]
array([1, 2])


In [ ]:
#lists and numpy arrays are different
data = np.zeros((5,2))
print(data)

data = np.zeros((5,2), dtype=int)
print(data)

#np.random.seed(5678)
data = np.random.randint(-5, high = 10, size = (5,2))
print(data)

one_row_as_list = [0,1]
data_as_list = [one_row_as_list]*5
print(data_as_list)
print(np.array(data_as_list))
print(np.array(data_as_list).shape)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[-5  0]
 [-2  5]
 [ 1  4]
 [-2 -2]
 [ 4  3]]
[[0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
(5, 2)


In [ ]:
x = np.array([1,2,3])
print(x.shape)
print(x)
print(x.T)

print()

x.resize((1,3))
print(x.shape)
print(x)
print(x.T)

print(x.T.shape)


(3,)
[1 2 3]
[1 2 3]

(1, 3)
[[1 2 3]]
[[1]
 [2]
 [3]]
(3, 1)


In [ ]:
x = [1,2]
y = [x,x]
z = y  #points to the same object
from copy import deepcopy
w = deepcopy(y)
print(y)
x[0]=5
print(y)
print(z)
print(w)
print(type(y[0]))

[[1, 2], [1, 2]]
[[5, 2], [5, 2]]
[[5, 2], [5, 2]]
[[1, 2], [1, 2]]
<class 'list'>


In [ ]:
a = [1,2]
b = [3,4]
x = np.array([a,b])
a[0]=5
print(x)

[[1 2]
 [3 4]]


In [ ]:
y = x.copy()
y[0,0] = 9
print(y)
print(x)


[[9 2]
 [3 4]]
[[9 2]
 [3 4]]


In [ ]:
np.array([[1,2,3],[4,5]])

<ipython-input-28-5aa9f74652b0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[4,5]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [ ]:
np.random.seed(5678)  # Setting seed for reproducibility

# Creating the 'x' values
x = np.linspace(0, 10, 101)

# Generating the 'r' values without noise
r_without_noise = x * 2

# Adding noise
noise1 = np.random.normal(0, .5, len(x))
r = r_without_noise + noise1

df_xr = pd.DataFrame({'x': x, 'r': r})


In [ ]:
pd.DataFrame({'x':[1,2,3], 'r':['aasd','asdasdf','qeqwe']})

x        r
0  1     aasd
1  2  asdasdf
2  3    qeqwe

In [ ]:
x=[0,1,2,3]
[a**2 for a in x]

[0, 1, 4, 9]

In [ ]:
noise1

array([-0.35489469, -0.00859559,  0.15970569, -1.13266554, -0.68872683,
        0.97499037, -0.28190504, -0.42186879,  0.11226929, -0.19568886,
        0.30275174, -0.34307517,  0.59168002,  0.27447841, -0.19810953,
        0.68685935, -0.10986341,  0.07987211,  0.48655119, -0.00424878,
        0.49546772, -0.72444396, -0.72564834,  0.38470069, -0.48247057,
        0.17832576,  0.29148321,  0.55065683, -0.31043193, -0.2134976 ,
       -0.66681424,  0.41883376, -0.88004733, -1.14213544,  0.49082748,
       -0.09192076, -0.10709561, -0.28966193,  0.16631557,  0.13857627,
        0.43658107, -0.82426881, -0.61649328, -1.01655349, -0.00469524,
        0.11662038,  0.43353611, -0.38872164,  0.25197681, -0.15069716,
       -1.07931311,  0.64828958,  0.48834133, -0.43599069, -0.48345722,
        0.00414193,  0.15070757, -0.4941407 , -0.55721211, -0.4090626 ,
        0.73994754, -0.79427949,  0.28119988,  0.27711185,  0.72649106,
        0.3423275 , -0.16400682,  1.16035564,  0.69057392,  0.35

In [ ]:
print(df_xr.head(10))
print()
print(df_xr.loc[3,'r'])
print()
print(df_xr.loc[1:3,['r','r','x','r']])
print()
print(df_xr.iloc[3,1])
print()
print(df_xr.iloc[1:3,[1,1]])

     x         r
0  0.0 -0.354895
1  0.1  0.191404
2  0.2  0.559706
3  0.3 -0.532666
4  0.4  0.111273
5  0.5  1.974990
6  0.6  0.918095
7  0.7  0.978131
8  0.8  1.712269
9  0.9  1.604311

-0.5326655356168191

          r         r    x         r
1  0.191404  0.191404  0.1  0.191404
2  0.559706  0.559706  0.2  0.559706
3 -0.532666 -0.532666  0.3 -0.532666

-0.5326655356168191

          r         r
1  0.191404  0.191404
2  0.559706  0.559706


In [ ]:
temp = df_xr.copy()
print(temp.index)

new_indices = ['row'+str(i) for i,idx in enumerate(temp.index)]
print(new_indices)

temp['new'] = new_indices
temp.set_index('new', inplace = True)

temp.head()
print(temp.loc['row3','r'])


RangeIndex(start=0, stop=101, step=1)
['row0', 'row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8', 'row9', 'row10', 'row11', 'row12', 'row13', 'row14', 'row15', 'row16', 'row17', 'row18', 'row19', 'row20', 'row21', 'row22', 'row23', 'row24', 'row25', 'row26', 'row27', 'row28', 'row29', 'row30', 'row31', 'row32', 'row33', 'row34', 'row35', 'row36', 'row37', 'row38', 'row39', 'row40', 'row41', 'row42', 'row43', 'row44', 'row45', 'row46', 'row47', 'row48', 'row49', 'row50', 'row51', 'row52', 'row53', 'row54', 'row55', 'row56', 'row57', 'row58', 'row59', 'row60', 'row61', 'row62', 'row63', 'row64', 'row65', 'row66', 'row67', 'row68', 'row69', 'row70', 'row71', 'row72', 'row73', 'row74', 'row75', 'row76', 'row77', 'row78', 'row79', 'row80', 'row81', 'row82', 'row83', 'row84', 'row85', 'row86', 'row87', 'row88', 'row89', 'row90', 'row91', 'row92', 'row93', 'row94', 'row95', 'row96', 'row97', 'row98', 'row99', 'row100']
-0.5326655356168191


In [ ]:
x = np.array([1,2,3])
print(x)
print(x := x.reshape((3,1)))
print(x)


[1 2 3]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [ ]:
a = [10,20,30,40,50,60]
a[1:5]
for i in range(3,5):
  print(i)

3
4


In [ ]:
df_xr.index

RangeIndex(start=0, stop=101, step=1)

In [ ]:
df_xr.index.to_numpy()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
df_xr.index.to_list()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
df_xr.set_index(df_xr.index+5, inplace = True)
print(df_xr.head(10))

      x         r
5   0.0 -0.354895
6   0.1  0.191404
7   0.2  0.559706
8   0.3 -0.532666
9   0.4  0.111273
10  0.5  1.974990
11  0.6  0.918095
12  0.7  0.978131
13  0.8  1.712269
14  0.9  1.604311


In [ ]:
print(r_without_noise.shape)
print(df_xr.values.shape)
print(type(df_xr))
print(type(df_xr.values))



(101,)
(101, 2)
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [ ]:
nd_array1 = np.column_stack((df_xr.values, r_without_noise))
nd_array2 = np.concatenate((df_xr.values, r_without_noise.reshape(-1,1)), axis=1)
nd_array3 = np.hstack((df_xr.values, r_without_noise.reshape(-1,1)))

print(nd_array1[0:5])
print(nd_array1[0:5,-1])
print(nd_array1[0:5][-1])


[[ 0.         -0.35489469  0.        ]
 [ 0.1         0.19140441  0.2       ]
 [ 0.2         0.55970569  0.4       ]
 [ 0.3        -0.53266554  0.6       ]
 [ 0.4         0.11127317  0.8       ]]
[0.  0.2 0.4 0.6 0.8]
[0.4        0.11127317 0.8       ]


In [ ]:
df_xr

x          r
5     0.0  -0.354895
6     0.1   0.191404
7     0.2   0.559706
8     0.3  -0.532666
9     0.4   0.111273
..    ...        ...
101   9.6  19.019764
102   9.7  19.956439
103   9.8  19.733286
104   9.9  20.334647
105  10.0  20.601071

[101 rows x 2 columns]

In [ ]:
nd_array1 == nd_array2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ T

In [ ]:
np.all(nd_array1 == nd_array2)

True

In [ ]:
np.all(nd_array1 == nd_array3)

True

In [ ]:
df_xr_01 = df_xr[(df_xr['r'] >= 0) & (df_xr['r'] <= 1)]
df_xr_01.head(10)

x         r
6   0.1  0.191404
7   0.2  0.559706
9   0.4  0.111273
11  0.6  0.918095
12  0.7  0.978131

In [ ]:
print(df_xr_01 := df_xr_01.reset_index().head())
#without the assignment operator, :=, it would simply return a new df (no change to the original df)

print(df_xr_01.head(10))

   level_0  index    x         r
0        0      6  0.1  0.191404
1        1      7  0.2  0.559706
2        2      9  0.4  0.111273
3        3     11  0.6  0.918095
4        4     12  0.7  0.978131
   level_0  index    x         r
0        0      6  0.1  0.191404
1        1      7  0.2  0.559706
2        2      9  0.4  0.111273
3        3     11  0.6  0.918095
4        4     12  0.7  0.978131


In [ ]:
df_xr_01.reset_index(inplace=True)
df_xr_01.head(10)

index    x         r
0      6  0.1  0.191404
1      7  0.2  0.559706
2      9  0.4  0.111273
3     11  0.6  0.918095
4     12  0.7  0.978131

In [ ]:
# Creating View2 with the 'y' and 'z' values
y = np.linspace(0, 10, 80)
z = np.linspace(5, 15, 80)

# Generating the 'r' values without noise
r_without_noise = 3*y - 6*z + 5

df2 = pd.DataFrame({'y': y, 'z': z, 'r': r_without_noise})


In [ ]:
# Adding noise
noise2 = np.random.normal(0, 1, len(y))
r = r_without_noise + noise2
df2['r_2'] = r

df3 = df2
df4 = df2.copy()   #deep copies automatically
df2.drop(columns = ['r'], inplace=True)


In [ ]:
print(df2.head())
print(df3.head())
print(df4.head())
df4.drop(columns = ['r'])
print(df4.head())


          y         z        r_2
0  0.000000  5.000000 -24.602546
1  0.126582  5.126582 -24.864764
2  0.253165  5.253165 -26.845273
3  0.379747  5.379747 -25.355285
4  0.506329  5.506329 -27.030058
          y         z        r_2
0  0.000000  5.000000 -24.602546
1  0.126582  5.126582 -24.864764
2  0.253165  5.253165 -26.845273
3  0.379747  5.379747 -25.355285
4  0.506329  5.506329 -27.030058
          y         z          r        r_2
0  0.000000  5.000000 -25.000000 -24.602546
1  0.126582  5.126582 -25.379747 -24.864764
2  0.253165  5.253165 -25.759494 -26.845273
3  0.379747  5.379747 -26.139241 -25.355285
4  0.506329  5.506329 -26.518987 -27.030058
          y         z          r        r_2
0  0.000000  5.000000 -25.000000 -24.602546
1  0.126582  5.126582 -25.379747 -24.864764
2  0.253165  5.253165 -25.759494 -26.845273
3  0.379747  5.379747 -26.139241 -25.355285
4  0.506329  5.506329 -26.518987 -27.030058
