<a href="https://colab.research.google.com/github/olcaykursun/ML/blob/main/Classification_report_ML_Spr2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.set_printoptions(precision=2)

from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

iris = datasets.load_iris()
X = iris.data
y = iris.target    #150 examples in total, y=0 setosa, y=1 versicolor, y=2 virginica

numclasses=len(iris.target_names)

print(iris.target_names[y])  #numpy arrays are usually easier to use (like arrays)
list_of_names = list(iris.target_names)
#print(list_of_names[y])     #this does not work
print(y)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.5, random_state=5, stratify=None)
print('Number of setosas in the training set', np.sum(y_train==0))


Number of setosas in the training set 28


In [3]:
print(iris.feature_names,', class-label')
print(np.c_[X,iris.target_names[y]])

mytest_flower = [6, 3, 4, 4]
print('What is the predicted class label for', mytest_flower, '?')

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] , class-label
[['5.1' '3.5' '1.4' '0.2' 'setosa']
 ['4.9' '3.0' '1.4' '0.2' 'setosa']
 ['4.7' '3.2' '1.3' '0.2' 'setosa']
 ['4.6' '3.1' '1.5' '0.2' 'setosa']
 ['5.0' '3.6' '1.4' '0.2' 'setosa']
 ['5.4' '3.9' '1.7' '0.4' 'setosa']
 ['4.6' '3.4' '1.4' '0.3' 'setosa']
 ['5.0' '3.4' '1.5' '0.2' 'setosa']
 ['4.4' '2.9' '1.4' '0.2' 'setosa']
 ['4.9' '3.1' '1.5' '0.1' 'setosa']
 ['5.4' '3.7' '1.5' '0.2' 'setosa']
 ['4.8' '3.4' '1.6' '0.2' 'setosa']
 ['4.8' '3.0' '1.4' '0.1' 'setosa']
 ['4.3' '3.0' '1.1' '0.1' 'setosa']
 ['5.8' '4.0' '1.2' '0.2' 'setosa']
 ['5.7' '4.4' '1.5' '0.4' 'setosa']
 ['5.4' '3.9' '1.3' '0.4' 'setosa']
 ['5.1' '3.5' '1.4' '0.3' 'setosa']
 ['5.7' '3.8' '1.7' '0.3' 'setosa']
 ['5.1' '3.8' '1.5' '0.3' 'setosa']
 ['5.4' '3.4' '1.7' '0.2' 'setosa']
 ['5.1' '3.7' '1.5' '0.4' 'setosa']
 ['4.6' '3.6' '1.0' '0.2' 'setosa']
 ['5.1' '3.3' '1.7' '0.5' 'setosa']
 ['4.8' '3.4' '1.9' '0.2' 'setosa']
 ['

In [4]:
X_train, X_test, y_train, y_test = train_test_split\
                                   (X, y, train_size=.5, random_state=5, stratify=y)
print('Number of setosas in the training set', np.sum(y_train==0))

test_count = len(y_test)
class_counts = np.array([sum(y_test==s) for s in range(numclasses)])
print(class_counts)


Number of setosas in the training set 25
[25 25 25]


In [5]:
clf=DecisionTreeClassifier(random_state=0)

clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

preds = clf.predict(X_test)
print(preds)
accuracy = np.mean(preds==y_test)
print(accuracy)

from sklearn.metrics import classification_report
report = classification_report(y_test, preds)
print(report)

predicted_class = clf.predict([mytest_flower])
predicted_class = predicted_class[0]   #we have a single test example here, pick that integer from the list
print('Predicted class label for', mytest_flower, 'is', iris.target_names[predicted_class])

0.96
[2 2 0 1 1 0 0 2 2 0 2 2 1 0 1 2 1 2 1 0 0 0 1 2 1 0 1 2 2 0 0 2 1 0 0 0 1
 2 2 1 1 0 2 2 2 0 2 2 1 1 0 1 2 0 0 1 0 1 1 2 0 2 2 0 0 2 2 1 1 1 0 1 1 2
 0]
0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.96      0.92      0.94        25
           2       0.92      0.96      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

Predicted class label for [6, 3, 4, 4] is versicolor


In [6]:
cnf_matrix = confusion_matrix(y_test, preds)
print('confusion matrix = ')
print(cnf_matrix)

# "N_" stands for "number_of_examples_"
N_predicted_as_that_class = cnf_matrix.sum(axis=0)
N_in_that_class = cnf_matrix.sum(axis=1)    #class_counts... row sums
N_correctly_classified_in_that_class = np.diag(cnf_matrix)

TP = N_correctly_classified_in_that_class
FP = N_predicted_as_that_class - N_correctly_classified_in_that_class
FN = N_in_that_class - N_correctly_classified_in_that_class
TN = cnf_matrix.sum() - (FP + FN + TP)
#TN = test_count - (FP + FN + TP)

print('TP TN FP FN for each class:')
print(np.stack((TP, TN, FP, FN),axis=1))


#Alternatively
myTP = np.zeros(numclasses)
myFP = np.zeros(numclasses)
myTN = np.zeros(numclasses)
myFN = np.zeros(numclasses)
for c in range(numclasses) :
  myTP[c] = sum(np.logical_and(y_test==c, preds==c))
  myFP[c] = sum(np.logical_and(y_test!=c, preds==c))
  myTN[c] = sum(np.logical_and(y_test!=c, preds!=c))
  myFN[c] = sum([x&y for (x,y) in zip(y_test==c, preds!=c)])  #built-in pythonic way without numpy
print('TP TN FP FN for each class:')
print(np.stack((myTP, myTN, myFP, myFN),axis=1))



FPRate = FP / (test_count - class_counts)
FNRate = FN / class_counts
TPRate = TP / class_counts
TNRate = TN / (test_count - class_counts)

print('TPRate',TPRate)
print('TNRate',TNRate)
print('FPRate',FPRate)
print('FNRate',FNRate)

Precision = TP/(TP+FP)
print('Precision', Precision)

Recall = TP/(TP+FN)
print('Recall', Recall)

from scipy import stats
print('F1 Score',stats.hmean([Precision, Recall]))  



confusion matrix = 
[[25  0  0]
 [ 0 23  2]
 [ 0  1 24]]
TP TN FP FN for each class:
[[25 50  0  0]
 [23 49  1  2]
 [24 48  2  1]]
TP TN FP FN for each class:
[[25. 50.  0.  0.]
 [23. 49.  1.  2.]
 [24. 48.  2.  1.]]
TPRate [1.   0.92 0.96]
TNRate [1.   0.98 0.96]
FPRate [0.   0.02 0.04]
FNRate [0.   0.08 0.04]
Precision [1.   0.96 0.92]
Recall [1.   0.92 0.96]
F1 Score [1.   0.94 0.94]
